### ISSUE TITLE
[Suggestion] Character Exp material calculator for the Experience Calculator 

### ISSUE THREAD

**Issue by MRDGH2821** [wing8169/genshin-impact-tracker#1]
I have a suggestion about this Character Experience calculator.

Suppose -
> Current Character Level
> 1
> Character Experience (At Current Level)
> 50
> Experience Materials (+ 1,000)
> 1
> Experience Materials (+ 5,000)
> 0
> Experience Materials (+ 20,000)
> 0
> Target Character Level
> 5

It shows - 
> Total Experience from the Materials: 1000
>Total Experience Needed to Level Up: 6125
>Total Mora Needed to Level Up: 1225
>Total Experience Remaining after Levelling: -5125

My idea is, from that "Total exp needed to level up" can be translated into how much [Adventurer's Experience, Hero's Wits, Wanderer's Advice](https://genshinimpact.wiki.fextralife.com/Materials) is required. And total trips required to Ley Line Outcrops (exp)

In this case, I need 6125.
The code can round it off to 7000.
Rounding off to greater number will accommodate any tidbits. 
For eg - some require 5467345 exp. Round off to next thousandth place = 5468000

Then the answer would be - 
>Wanderer's Advice = 2x
>Adventurer's Experience = 1x
>Hero's Wit = 0x

We also have Ley Line Outcrop (Exp). Those Blue in colour.
These give 13~14 Adventurer's Exp material.
Let's take it 13 to simplify things.
So, In this case, the output should be - 
>Ley Line Outcrop (exp) trips = 1x
>Original Resin cost = 20

Logic for the trips -
The round off we found for exp = 7000 xp.
Adventurer's exp = 5000 xp.

Here we do another round off to ten thousandth. 
So, we have -
New round off we found for exp = 10000 xp.
Adventurer's Exp required (Dividing it by 5000) = 2x

```
if ( "Adventurer's Exp required" > "13x")
{
  it = "Adventurer's Exp required"
  "Ley line outcrop(exp) trips" = divide it by 13. Round it off to next integer. 
}
else
{
 "Ley line outcrop(exp) trips" = 1x
  "Original Resin cost" = 20 * "Ley line outcrop(exp) trips"
}
```

Example 124x AE is required. 
Divide by 13 = 9.534...
Trips = 10
Resin = 20*10 = 200

You can do further calculations about refreshing resin (or resin refills) and all, but that would be tiresome as of now 😅
That can be put in next version after you implement the above one 😅😅

**Comment by wing8169** [comment]
Hi @MRDGH2821 Thanks for the detailed suggestion! I am spamming resins for character experience books right now at AR 41, wish to know when is the end too, will implement this with a bit more details (rewards for ley line crops differ according to AR).

**Comment by MRDGH2821** [comment]
If it differs according to AR Rank, then you can ask the user itself how much exp materials they get if they finish 1 Ley Line Outcrop (Exp) 🤔

I'm AR 35 and I get 13~14.

If I knew how to code in JS, I would have done changes myself😅😅

**Comment by wing8169** [comment]
Closed the issue, implemented and deployed experience calculation together with the leyline tip calculation, also minor change in which now experience calculator does not require log in.

![image](https://user-images.githubusercontent.com/33794617/97861415-b104ed00-1d3e-11eb-84b6-6f990a7ad923.png)

Need more resins!!

**Comment by MRDGH2821** [comment]
<Amber's idle voice over> That's more Like it!

<After calculating trips & seeing resins> That's cheating!

Anyways, Nice addition!

I will "raise issue" when I have another suggestion!
